config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  scope module: :web do
    root 'bulletins#index'

    resources :bulletins do
      member do
        patch :moderate, :archive
      end
    end

    resource :profile, only: :show

    post 'auth/sign_out', to: 'auth#sign_out', as: :sign_out
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    namespace :admin do
      root 'home#index'
      resources :categories

      resources :bulletins, only: :index do
        member do
          patch :publish, :reject, :archive
        end
      end
    end
  end
end

app/views/web/admin/shared/_sidebar.html.slim
.col-md-3
  ul.nav.flex-column.nav-pills
    li.nav-item
      = link_to admin_root_path,
              class: class_names(['nav-link', 'link-dark', { active: current_page?(admin_root_path) }]) do
        = t('.on_moderated')
    li.nav-item
      = link_to admin_bulletins_path,
              class: class_names(['nav-link', 'link-dark', { active: current_page?(admin_bulletins_path) }]) do
        = t('.all_bulletins')
    li.nav-item
      = link_to admin_categories_path,
              class: class_names(['nav-link', 'link-dark', { active: current_page?(admin_categories_path) }]) do
        = t('.categories')