config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  scope module: :web do
    root 'bulletins#index'

    resources :bulletins do
      member do
        patch :moderate, :archive
      end
    end

    resource :profile, only: :show

    post 'auth/sign_out', to: 'auth#sign_out', as: :sign_out
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    namespace :admin do
      root 'home#index'
      resources :categories

      resources :bulletins, only: :index do
        member do
          patch :publish, :reject, :archive
        end
      end
    end
  end
end

app/controllers/web/admin/home_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class HomeController < Web::Admin::ApplicationController
      def index
        @bulletins = Bulletin.under_moderation.desc_by_created.page(params[:page])
      end
    end
  end
end

app/views/web/admin/home/index.html.slim
.row
  = render 'web/admin/shared/sidebar'
  .col-md-9
    h1.h2.mb-4 = t('.title')
    row.mt-2
      table.table.table-borderless
        thead
          tr
            th = t('.name')
            th = t('.created')
            th = t('.actions')
        tbody
          - @bulletins.each do |bulletin|
            tr
              td
                = link_to bulletin_path(bulletin) do
                  = bulletin.title
              td
                = time_ago_in_words bulletin.created_at
              td
                - if bulletin.may_publish?
                  = link_to publish_admin_bulletin_path(bulletin),
                          data: { turbo_method: 'patch', turbo_confirm: t('.confirm_publish') },
                          class: 'me-1' do
                    = t('.publish')
                - if bulletin.may_reject?
                  = link_to reject_admin_bulletin_path(bulletin),
                          data: { turbo_method: 'patch', turbo_confirm: t('.confirm_rejecting') },
                          class: 'me-1' do
                    = t('.reject')
                - if bulletin.may_archive?
                  = link_to archive_admin_bulletin_path(bulletin),
                          data: { turbo_method: 'patch', turbo_confirm: t('.confirm_archiving') },
                          class: 'text-danger' do
                    = t('.archive')
      .mt-2
        = paginate @bulletins