config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  scope module: :web do
    root 'bulletins#index'

    resources :bulletins do
      member do
        patch :moderate, :archive
      end
    end

    resource :profile, only: :show

    post 'auth/sign_out', to: 'auth#sign_out', as: :sign_out
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    namespace :admin do
      root 'home#index'
      resources :categories

      resources :bulletins, only: :index do
        member do
          patch :publish, :reject, :archive
        end
      end
    end
  end
end

app/controllers/web/profiles_controller.rb
# frozen_string_literal: true

module Web
  class ProfilesController < Web::ApplicationController
    before_action :authorize_user

    def show
      @query = current_user.bulletins.ransack(params[:q])
      @bulletins = @query.result.desc_by_created.page(params[:page])
    end
  end
end

app/views/web/profiles/_search.html.slim
= search_form_for query, url: do |f|
  .row.my-2
    .col-5
      = f.input :title_cont,
              label: t('.by_name'),
              placeholder: false
    .col-4
      = f.input :state_eq,
              as: :select,
              collection: Bulletin.aasm.states,
              value_method: :name,
              label_method: :human_name,
              label: t('.by_state')
    .col-3.mt-4
      = f.submit t('buttons.search'), class: 'btn btn-primary me-2'
      = link_to t('buttons.reset'), url_for, class: 'btn btn-outline-primary'

app/views/web/profiles/show.html.slim
.row
  .p-3.p-lg-5.pt-lg-0
    .mb-4
      h2 = t('.title')
      hr
    = link_to new_bulletin_path do
      = t('.add_bulletin')
    == render 'search', query: @query, url: profile_path
    .row.mt-2
      table.table.table-borderless
        thead
          tr
            th = t('.name')
            th = t('.state')
            th = t('.created')
            th = t('.actions')
        tbody
          - @bulletins.each do |bulletin|
            tr
              td
                = bulletin.title
              td
                = t(".states.#{bulletin.state}")
              td
                = time_ago_in_words bulletin.created_at
              td
                = link_to bulletin_path(bulletin), class: 'me-2' do
                  = t('.show')
                = link_to edit_bulletin_path(bulletin), class: 'me-2' do
                  = t('.edit')
                - if bulletin.may_moderate?
                  = link_to moderate_bulletin_path(bulletin),
                          data: { turbo_method: 'patch' },
                          class: 'me-2' do
                    = t('.moderate')
                - if bulletin.may_archive?
                  = link_to archive_bulletin_path(bulletin),
                          data: { turbo_method: 'patch', turbo_confirm: t('.confirm_archiving') },
                          class: 'text-danger' do
                    = t('.archive')
    .mt-2
      = paginate @bulletins