config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  scope module: :web do
    root 'bulletins#index'

    resources :bulletins do
      member do
        patch :moderate, :archive
      end
    end

    resource :profile, only: :show

    post 'auth/sign_out', to: 'auth#sign_out', as: :sign_out
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    namespace :admin do
      root 'home#index'
      resources :categories

      resources :bulletins, only: :index do
        member do
          patch :publish, :reject, :archive
        end
      end
    end
  end
end

app/views/layouts/_header.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4' do
        = t('.title')
      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          li.nav-item.me-2
            = link_to root_path, class: 'nav-link text-dark' do
              = t('.home')
          - if authorized?
            li.nav-item.me-2
              = link_to profile_path, class: 'nav-link text-dark' do
                = t('.my_bulletins')
            li.nav-item.me-2
              = link_to new_bulletin_path, class: 'nav-link text-dark' do
                = t('.add_bulletin')
    ul.nav.nav-pills
      - if authorized?
        - if admin?
          li.nav-item.me-2
            = link_to admin_root_path, class: 'nav-link text-dark' do
              = t('.admin')
        li.nav-item.me-2
          = link_to sign_out_path, data: { turbo_method: :post }, class: 'nav-link text-dark' do
            = t('.sign_out')
      - else
        li.nav-item.me-2
          = button_to auth_request_path('github'), data: { turbo: false }, class: 'nav-link text-dark' do
            span.bi.bi-github.me-2
            = t('.sign_in')

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = t('.title')
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'

  body.d-flex.flex-column
    = render 'layouts/header'
    main
      .mt-4.mb-5.pb-5
        .container
          = render_flash_messages
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            = yield